kind: Service
apiVersion: v1
metadata:
  name: spring-gql-service
spec:
  selector:
    app: spring-gql
  ports:
    - name: spring-gql-service
      protocol: TCP
      port: 8080
      targetPort: 8080 # port of pod