apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  storageClassName: mongodb-storage-class
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: mongodb-pvc
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /Users/19057499/local-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - minikube